# Server Port
server.port=8081

# SQL Server Database Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bookstore;TrustServerCertificate=true;encrypt=false;sendStringParametersAsUnicode=true
spring.datasource.username=bookstore_user
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA & Hibernate Configuration
# Update database schema automatically
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.use_nationalized_character_data=true

# Show SQL logs in console for debugging
spring.jpa.show-sql=true

# Format the SQL logs
spring.jpa.properties.hibernate.format_sql=true

# Dialect for SQL Server
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
